-- #######################################################################################
-- HYPRLAND LUA CONFIGURATION ENTRYPOINT
-- #######################################################################################

-- Set up applications and paths
status_bar = "quickshell -d -p ~/.config/quickshell/01-bar.qml"
terminal = "alacritty"
fileManager = "thunar"
fileManagerDaemon = "thunar --daemon"
launcher = "fuzzel"
browser = "brave"
grimshot = "grimshot"
emoji_picker = "/home/marco/code/emoji/emoji-picker /home/marco/code/emoji/unicode_17_emojis.json"
notification_daemon = "dunst"
gui_finder = "fsearch"

-- Autostart services and programs
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd(status_bar)
    hl.exec_cmd(notification_daemon)
    hl.exec_cmd(fileManagerDaemon)
    hl.exec_cmd(terminal)
    hl.exec_cmd(browser)
end)

-- Debug settings
hl.config({
    debug = {
        disable_logs = false,
    }
})

-- Monitor configuration
hl.monitor({
    output   = "",
    mode     = "3840x2160@60",
    position = "auto",
    scale    = 1.5,
})

-- XWayland configuration
hl.config({
    xwayland = {
        force_zero_scaling = true,
        use_nearest_neighbor = true,
    }
})

-- Import environmental variables
require("hyprland_envvars")

-- Import gaming mouse custom profile
require("hyprland_mouse")

-- Load dynamic colors generated by wallust
local colors = require("hyprland_colors")

-- Look and Feel
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 1,
        resize_on_border = true,
        extend_border_grab_area = 15,
        hover_icon_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
        snap = {
            enabled = false,
        },
        col = {
            active_border = colors.active_border,
            inactive_border = colors.inactive_border,
        }
    },
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        dim_inactive = false,
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        }
    },
    animations = {
        enabled = true,
    }
})

-- Disable window and fade animations
hl.animation({ leaf = "windows", enabled = false })
hl.animation({ leaf = "windowsIn", enabled = false })
hl.animation({ leaf = "windowsOut", enabled = false })
hl.animation({ leaf = "windowsMove", enabled = false })
hl.animation({ leaf = "fade", enabled = false })
hl.animation({ leaf = "border", enabled = false })
hl.animation({ leaf = "borderangle", enabled = false })

-- Enable only workspace animations
hl.animation({ leaf = "workspaces", enabled = true, speed = 1, bezier = "default", style = "slide" })

-- Dwindle layout configurations
hl.config({
    dwindle = {
        preserve_split = true,
        force_split = 2,
    }
})

-- Miscellaneous configurations
hl.config({
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    }
})

-- Input configuration
hl.config({
    input = {
        kb_layout = "it",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
        repeat_delay = 300,
        repeat_rate = 50,
    }
})

-- Import window rules and keybindings
require("hyprland_rules")
require("hyprland_keybinds")
