-- Generated by wallust
return {
    active_border = {
        colors = {
            "rgb(D31A0C)",
            "rgb(E84606)",
            "rgb(E45D0D)"
        },
        angle = 45
    },
    inactive_border = "rgba(3E3A3Aee)"
}
